### ISSUE TITLE
Add a Celery support

### ISSUE THREAD

**Issue by sakost** [DaniloZZZ/tgflow#5]
It will be gratefull, if this lib can support a celery tasks.
Some code of adding a task should be like this:
```python
def func(i, s, **d):
    @tgflow.task()
    def celery_task(i, s, **d):  # some arguments
        return States.TIME_LIMIT_EXCEED, d
    task = celery_task()
    tgflow.schedule(task, 30*60)  # 30 minutes
    return States.DO_IN_30_MIN, d
```

**Comment by danlkv** [comment]
Sounds really awesome! I'll do it (someday)

**Comment by danlkv** [comment]
Hi, it seems that there's no need for this, you can now use ordinary `time.sleep()`function and `tgf.send_state()` to send a delayed notification. Check out an example: https://github.com/DaniloZZZ/tgflow/blob/master/examples/delayed.py

**Comment by sakost** [comment]
It's not what I meant
My example implies that you can change states before the task started
It is a notification feature, so it may be more correct not to allow to change the current state
My fixed example:
```python
def func(i, s, **d):
    @tgflow.task(change_state=False)  # if True then function must contain a return statement
    def celery_task(i, s, **d):  # some arguments
        # doing something
        return # "return States.SUCCESS, d" if "change_state" is True
    task = celery_task()
    tgflow.schedule(task, 30*60)  # 30 minutes
    return States.NEXT_STATE, d

**Comment by danlkv** [comment]
If you don't want to change state on notification, you can send a raw message:

A modified code from [example](https://github.com/DaniloZZZ/tgflow/blob/master/examples/delayed.py) will be:
```python
def handle_delay(i, s, **d):
    delay = int(i.text)
    tgf.send_state(States.SET, i.from_user.id, data = {'delay':delay})
    print("sleeping for",delay)
    time.sleep(delay)
    tgf.send_raw("Notification!", i.user.id)
    print("done",delay)
    return States.MENU, {'notification_sent':true}
```

**Comment by sakost** [comment]
> If you don't want to change state on notification, you can send a raw message:
> 
> A modified code from [example](https://github.com/DaniloZZZ/tgflow/blob/master/examples/delayed.py) will be:
> 
> ```python
> def handle_delay(i, s, **d):
>     delay = int(i.text)
>     tgf.send_state(States.SET, i.from_user.id, data = {'delay':delay})
>     print("sleeping for",delay)
>     time.sleep(delay)
>     tgf.send_raw("Notification!", i.user.id)
>     print("done",delay)
>     return States.MENU, {'notification_sent':true}
> ```

But it will be block the thread, isn't it? and so you will not receive updates from server at that moment

**Comment by danlkv** [comment]
No, it seems that telebot is handling a connection in a separate thread. I haven't tested for other platforms, though, but telegram works ok.

**Comment by sakost** [comment]
okey. then I close the issue.
